name: Makefile CI
on: [workflow_dispatch]
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: release
    - name: install SDL2
      run: sudo apt-get install libsdl2-2.0-0 libsdl2-image-2.0-0 libsdl2-ttf-2.0-0 libsdl2-mixer-2.0-0
    - name: setup SBCL
      run: sudo apt-get install sbcl
    - name: install quicklisp
      run: |
        curl -O https://beta.quicklisp.org/quicklisp.lisp
        sbcl --load quicklisp.lisp --eval "(quicklisp-quickstart:install)" --eval "(ql-util:without-prompting (ql:add-to-init-file))" --eval "(print ql:*quicklisp-home*)" --eval "(print (user-homedir-pathname))" --quit
    - name: install sketch & cl-sdl2 & sdl2.kit from source
      run: |
        cd quicklisp/local-projects/ # FIXME
        git clone https://github.com/Gleefre/sketch # To have resizable windows; FIXME later
        git clone https://github.com/Gleefre/cl-sdl2 # FIXME: https://github.com/lispgames/cl-sdl2
        git clone https://github.com/lispgames/sdl2kit
        git clone https://github.com/lispgames/cl-sdl2-mixer
    - name: build
      run: make
    - name: zip
      run: |
        rm -f linux-bin.zip
        zip linux-bin.zip bin/*
        rm -rf bin
    - name: git add, commit, push
      run: |
        git config --global user.name 'Gleefre'
        git config --global user.email 'Gleefre@users.noreply.github.com'
        git add linux-bin.zip
        git commit -am "release-linux"
        git push
