name: Makefile CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        lisp: [sbcl-bin]
        os:
          - windows-latest
          #- ubuntu-latest
          #- macos-latest

    runs-on: ${{ matrix.os }}

    env:
      LISP: ${{ matrix.lisp }}

    steps:

    - uses: 40ants/setup-lisp@v2
      with:
          asdf-system: cl-info
    - uses: actions/checkout@v3
    - name: Grant All Perms to Make Cache Restoring Possible
      run: |
        sudo mkdir -p /usr/local/etc/roswell
        sudo chown "${USER}" /usr/local/etc/roswell
        # Here the ros binary will be restored:
        sudo chown "${USER}" /usr/local/bin
    - name: Get Current Month
      id: current-month
      run: |
        echo "::set-output name=value::$(date -u "+%Y-%m")"
    - name: Cache Roswell Setup
      id: cache
      uses: actions/cache@v2
      env:
        cache-name: cache-roswell
      with:
        path: |
          /usr/local/bin/ros
          ~/.cache/common-lisp/
          ~/.roswell
          /usr/local/etc/roswell
          .qlot
        key: "${{ steps.current-month.outputs.value }}-${{ env.cache-name }}-${{ runner.os }}-${{ hashFiles('qlfile.lock') }}"
    - name: Restore Path To Cached Files
      run: |
        echo $HOME/.roswell/bin >> $GITHUB_PATH
        echo .qlot/bin >> $GITHUB_PATH
      if: steps.cache.outputs.cache-hit == 'true'
    - uses: 40ants/setup-lisp@v2
      if: steps.cache.outputs.cache-hit != 'true'

    - name: install-sdl2-linux
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get install libsdl2-2.0-0 libsdl2-image-2.0-0 libsdl2-ttf-2.0-0 libsdl2-mixer-2.0-0

    - name: prepare-sdl2-install-windows
      run: |
        mkdir sdl2-bin
        export LD_LIBRARY_PATH=sdl2-bin
    - name: install-sdl2-windows
      if: matrix.os == 'windows-latest'
      uses: albin-johansson/download-sdl2@v2
      with:
          sources_destination: .
          binaries_destination: sdl2-bin
    - name: install-sdl2-image-windows
      if: matrix.os == 'windows-latest'
      uses: albin-johansson/download-sdl2-image@v2
      with:
          sources_destination: .
          binaries_destination: sdl2-bin
    - name: install-sdl2-ttf-windows
      if: matrix.os == 'windows-latest'
      uses: albin-johansson/download-sdl2-ttf@v1
      with:
          sources_destination: .
          binaries_destination: sdl2-bin
    - name: install-sdl2-mixer-windows
      if: matrix.os == 'windows-latest'
      uses: albin-johansson/download-sdl2-mixer@v1
      with:
          sources_destination: .
          binaries_destination: sdl2-bin      
      
    - name: Build
      run: |
        ros -e "(ql:quickload :deploy)" -e "(ql:quickload :asdf)" -e "(ql:quickload :sb-cga)" -l test-ga.asd -e "(asdf:load-system :test-ga :force t)" -e "(asdf:make :test-ga)"

    - name: zip
      run: |
        zip ${{ runner.os }}-bin.zip bin/*
  
    - name: make clean
      run: make clean

    - name: git add and commit
      run: |
        git checkout release
        git add ${{ runner.os }}-bin.zip
        git commit -m "Does it work?"
