name: Makefile CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os:
          #- ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
      with:
        ref: release

    - name: install-sdl2-linux
      if: matrix.os == 'linux-latest'
      run: sudo apt-get install libsdl2-2.0-0 libsdl2-image-2.0-0 libsdl2-ttf-2.0-0 libsdl2-mixer-2.0-0

    - name: install sbcl linux
      if: matrix.os == 'linux-latest'
      uses: cheeze2000/setup-sbcl@v1

    - name: install sbcl windows
      if: matrix.os == 'windows-latest'
      run: choco install sbcl

    - name: Setup MSYS2; install sdl2
      if: matrix.os == 'windows-latest'
      uses: msys2/setup-msys2@v2
      with:
        install: mingw-w64-x86_64-gcc make diffutils git mingw-w64-x86_64-SDL2 mingw-w64-x86_64-SDL2_image mingw-w64-x86_64-SDL2_ttf mingw-w64-x86_64-SDL2_mixer

    - name: intall quicklisp
      if: matrix.os == 'windows-latest'
      run: |
        curl -O https://beta.quicklisp.org/quicklisp.lisp
        sbcl --non-interactive --load quicklisp.lisp --eval "(quicklisp-quickstart:install)" --eval "(ql-util:without-prompting (ql:add-to-init-file))"
      shell: bash

    - name: morehel
      run: ls D:/a/_temp/msys64/mingw64/lib
      shell: bash

    - name: WinBuild
      if: matrix.os == 'windows-latest'
      run: make
      env: 
        LD_LIBRARY_PATH: D:\\a\_temp\msys64\mingw64\lib

    - name: WinBuild - path?
      if: matrix.os == 'windows-latest'
      run: make
      env: 
        PATH: D:\\a\_temp\msys64\mingw64\lib

    - name: LinBuild
      if: matrix.os != 'windows-latest'
      run: make

    - name: clean old zip
      run: rm -f ${{ runner.os }}-bin.zip
      shell: bash
    - name: create new zip
      run: zip ${{ runner.os }}-bin.zip bin/*

    - name: (w|h)ell
      run: git status
    - name: (w|h)ell - 2
      run: git add ${{ runner.os }}-bin.zip
    - name: (w|h)ell - 3
      run: git status

    - name: Git Commit and Push
      run: |
          git config --global user.name 'Gleefre'
          git config --global user.email 'Gleefre@users.noreply.github.com'
          git commit -am "Does it workp"
          git push
