name: Makefile CI

on:
  push:
    branches: [ "main" ]

jobs:
#   build-linux:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#       with:
#         ref: release
#     - name: install SDL2
#       run: sudo apt-get install libsdl2-2.0-0 libsdl2-image-2.0-0 libsdl2-ttf-2.0-0 libsdl2-mixer-2.0-0
#     - name: setup SBCL
#       uses: cheeze2000/setup-sbcl@v1
#     - name: build
#       run: make
#     - name: zip
#       run: |
#         rm -f linux-bin.zip
#         zip linux-bin.zip bin/*
#         rm -rf bin
#     - name: git add, commit, push
#       run: |
#         git config --global user.name 'Gleefre'
#         git config --global user.email 'Gleefre@users.noreply.github.com'
#         git add linux-bin.zip
#         git commit -am "release-linux"
#         git push

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: release
    - name: install SBCL & pkgconfig & mingw
      run: choco install sbcl pkgconfiglite mingw wget

    - name: install libffi
      shell: bash
      run: |
        wget https://github.com/libffi/libffi/releases/download/v3.4.4/libffi-3.4.4.tar.gz
        tar -xf libffi-3.4.4.tar.gz
        cd libffi-3.4.4/
        sh ./configure --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32
        make
        sudo make install

    - name: install quicklisp
      run: |
        curl -O https://beta.quicklisp.org/quicklisp.lisp
        sbcl --non-interactive --load quicklisp.lisp --eval "(quicklisp-quickstart:install)" --eval "(ql-util:without-prompting (ql:add-to-init-file))"
      shell: bash
    - name: download SDL2
      uses: albin-johansson/download-sdl2@v2
      with:
        sources_destination: .
        binaries_destination: .
    - name: download SDL2-IMAGE
      uses: albin-johansson/download-sdl2-image@v2
      with:
        sources_destination: .
        binaries_destination: .
    - name: download SDL-TTF
      uses: albin-johansson/download-sdl2-ttf@v1
      with:
        sources_destination: .
        binaries_destination: .
    - name: download SDL2-MIXER
      uses: albin-johansson/download-sdl2-mixer@v1
      with:
        sources_destination: .
        binaries_destination: .

    - run: |
        rm -rf bin/
        mkdir bin/
        cp Makefile bin/
      shell: bash

    - name: build
      run: make

    - name: clean old zip
      run: rm -f ${{ runner.os }}-bin.zip
      shell: bash
    - name: create new zip (windows)
      run: Compress-Archive -Path .\bin -DestinationPath .\windows-bin

    - name: Git Commit and Push
      run: |
          git status
          git add windows-bin.zip
          git config --global user.name 'Gleefre'
          git config --global user.email 'Gleefre@users.noreply.github.com'
          git commit -am "Does it workp"
          git push

#     - name: Setup MSYS2; install sdl2
#      if: matrix.os == 'windows-latest'
#      uses: msys2/setup-msys2@v2
#      with:
#        install: mingw-w64-x86_64-gcc make diffutils git mingw-w64-x86_64-SDL2 mingw-w64-x86_64-SDL2_image mingw-w64-x86_64-SDL2_ttf mingw-w64-x86_64-SDL2_mixer
#     - name: Windows - path?
#      if: matrix.os == 'windows-latest'
#      uses: myci-actions/export-env-var-powershell@1
#      with:
#        name: PATH
#        value: $env:PATH;D:\a\_temp\msys64\mingw64\lib
#     - name: Setup MSYS2?..
#      if: matrix.os == 'windows-latest'
#      uses: msys2/setup-msys2@v2
#      with:
#        install: mingw-w64-x86_64-gcc make diffutils git
#     - name: hohoho
#       run: ls
