name: Makefile CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: release

    - name: install sbcl linux
      uses: cheeze2000/setup-sbcl@v1

    - name: install-sdl2-linux
      run: sudo apt-get install libsdl2-2.0-0 libsdl2-image-2.0-0 libsdl2-ttf-2.0-0 libsdl2-mixer-2.0-0

    - name: Build
      run: make

    - name: zip
      run: zip ${{ runner.os }}-bin.zip bin/*
      
    - name: (w|h)ell
      run: |
        git status
        git add ${{ runner.os }}-bin.zip
  
    - name: Git Commit and Push
      uses: github-actions-x/commit@v2.9
      with:
        # Github Token with commit access
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: release
        commit-message: hopefullyfine
        files: ${{ runner.os }}-bin.zip
