name: Makefile CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: release

    - name: install sbcl linux
      uses: cheeze2000/setup-sbcl@v1

    - name: install-sdl2-linux
      run: sudo apt-get install libsdl2-2.0-0 libsdl2-image-2.0-0 libsdl2-ttf-2.0-0 libsdl2-mixer-2.0-0

    - name: Build
      run: make

    - name: zip
      run: zip ${{ runner.os }}-bin.zip bin/*
      
    - name: (w|h)ell
      run: git status
    - name: (w|h)ell - 2
      run: git add ${{ runner.os }}-bin.zip
    - name: (w|h)ell - 3
      run: git status

    - name: Git Commit and Push
      run: |
          git config --global user.name 'Gleefre'
          git config --global user.email 'Gleefre@users.noreply.github.com'
          git commit -am "Does it workp"
          git push
