name: Makefile CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install sbcl linux
      uses: cheeze2000/setup-sbcl@v1

    - name: install-sdl2-linux
      run: sudo apt-get install libsdl2-2.0-0 libsdl2-image-2.0-0 libsdl2-ttf-2.0-0 libsdl2-mixer-2.0-0

    - name: Build
      run: make

    - name: zip
      run: zip ${{ runner.os }}-bin.zip bin
  
    - name: make clean
      run: make clean

    - name: git checkout release
      uses: actions/checkout@v3
      with:
        ref: release
    - name: aaa
      run: |
        git add ${{ runner.os }}-bin.zip
        git commit -m "Does it work?"
        git push
