name: Makefile CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
      with:
        ref: release

    - name: install msys2
      uses: msys2/setup-msys2@v2
      with:
        install: mingw-w64-x86_64-libffi
  
    - name: install sbcl
      run: choco install sbcl

    - name: install quicklisp
      run: |
        curl -O https://beta.quicklisp.org/quicklisp.lisp
        C:/ProgramData/chocolatey/bin/sbcl.exe --non-interactive --load quicklisp.lisp --eval "(quicklisp-quickstart:install)" --eval "(ql-util:without-prompting (ql:add-to-init-file))"
      shell: msys2 {0}

    - name: download SDL2
      uses: albin-johansson/download-sdl2@v2
      with:
        sources_destination: .
        binaries_destination: .
    - name: download SDL2-IMAGE
      uses: albin-johansson/download-sdl2-image@v2
      with:
        sources_destination: .
        binaries_destination: .
    - name: download SDL-TTF
      uses: albin-johansson/download-sdl2-ttf@v1
      with:
        sources_destination: .
        binaries_destination: .
    - name: download SDL2-MIXER
      uses: albin-johansson/download-sdl2-mixer@v1
      with:
        sources_destination: .
        binaries_destination: .
  
    - name: prep
      run: |
        rm -rf bin/
        mkdir bin/
        cp Makefile bin/
      shell: msys2 {0}

    - name: build
      run: LISP=C:/ProgramData/chocolatey/bin/sbcl.exe make
      shell: msys2 {0}

    - name: clean old zip
      run: rm -f windows-bin.zip
      shell: bash

    - name: create new zip (windows)
      run: Compress-Archive -Path .\bin -DestinationPath .\windows-bin

    - name: Git Commit and Push
      run: |
          git status
          git add windows-bin.zip
          git config --global user.name 'Gleefre'
          git config --global user.email 'Gleefre@users.noreply.github.com'
          git commit -am "Does it workp"
          git push
